
scalar DateTime
scalar Date


type Author { 
    id: Int!
    firstName: String
    lastName: String
    """
    the list of Subjects by this author
    """
    Subjects: [Subject]
}

type Subject {
    id: Int!
    title: String
    content: String
    author: Author
}

enum UserInputType {
    QUESTION
    ANSWER
    COMMENT
    FEEDBACK
    STATEMENT
    SUGGESTION
    IDEA
}

type UserMessage {
    id: Int!
    content: String
    author: Author!
    subject: Subject!
    createdAt: Date!
    updatedAt: Date!
    type: UserInputType
}


type Query {
    subjects: [Subject]
    author(id: Int!): Author
    authorByName(firstName: String!, lastName: String!): Author
    authors: [Author]
    userInputsBySubject(id: Int!): [UserMessage]
}


type Mutation {
    createSubject(input: CreateSubject!): Subject
    createUserInput(input: CreateUserInput!): Boolean
}

input CreateSubject {
    title: String
    content: String
}

input CreateUserInput {
    author: Int!
    subject: Int!
    content: String!
    type: UserInputType!
    sentAt: Date!
}

type Subscription {
  userInputCreated: UserMessage
}